name: Keep Bot Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -s https://improvement-5zlq.onrender.com
